=== BlessedAndy/webservice/webservice_01/src/com/aitequ/dtd/ClassRoom.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT classroom (ClaName,grade,students)>
<!ATTLIST classroom id ID #REQUIRED>
<!ELEMENT ClaName (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT students (student+)>
<!ELEMENT student (id,StuName,age)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT StuName (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== BlessedAndy/webservice/webservice_01/src/com/aitequ/dtd/ClassRoom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classroom SYSTEM "ClassRoom.dtd">
<classroom id="classroom1">
	<ClaName>CS</ClaName>
	<grade>2012</grade>
	<students>
		<student>
			<id>123</id>
			<StuName>andy</StuName>
			<age>27</age>
		</student>
		<student>
			<id>234</id>
			<StuName>bonnie</StuName>
			<age>25</age>
		</student>
	</students>

</classroom>
